dylants/price-finder

- README.md
- lib/sites/priceminister.js
- test/e2e/priceminister-uris-test.js
- test/unit/sites/priceminister-test.js
This pull request represents the work that was done in #4, but has been squashed to a single commit for all work done by @Shuunen (thank you again!).  I've also included a unit test for the PriceMinister site.
By merging this pull request, there will be no need to merge #4 since that work is contained within this pull request (they are the same, but of course this one has the additional commit).
> Add priceminister site

- README.md
- lib/price-finder.js
- lib/site-manager.js
- lib/sites/best-buy.js
- test/e2e/best-buy-uris-test.js
- test/unit/sites/best-buy-test.js
- test/unit/sites/mock-data/bestbuy-other_category.json
- test/unit/sites/mock-data/bestbuy.full.json
Converted the script to rely on the data from the [API](https://developer.bestbuy.com/). Several changes were necessary to enable this:
* Adding a "keys" object to the configuration mechanism to make passing API keys to various sites easier (it also recognizes environment variables.)
* Passed the top-level config object to all known sites
* Uses some mock data to clean up the unit testing situations (put into a different directory versus stringifying the JSON)
> Update script to use Best Buy's API

- CHANGELOG.md
Include all past release information in the changelog.
> Fully populate the changelog

- README.md
- lib/site-utils.js
- lib/sites/ebags.js
- test/e2e/ebags-uris-test.js
- test/unit/sites/ebags-test.js
Add support for the luggage site, eBags.com
> Add support for eBags.com

- lib/site-utils.js
- lib/sites/newegg.js
- test/e2e/newegg-uris-test.js
- test/unit/sites/newegg-test.js
Added Support for NewEgg with test cases.
> NewEgg support

- lib/site-utils.js
- lib/sites/infibeam.js
- test/e2e/infibeam-uris-test.js
- test/unit/site-utils-test.js
- test/unit/sites/infibeam-test.js
Sorry for the trouble @dylants . Since I lost touch with git couple of years ago, I'm kinda screw things up with git. Since I can't able to re-base, I'm moving all those changes in a single commit!
> Infibeam Support Commit

- CHANGELOG.md
- README.md
- package.json
Update changelog (at least the most recent changes) to give credit to those who have added to the project.  Also move to a better standard to display changes.
Update readme to include additional supported sites.
> Release 3.1.0

- README.md
Specify the master branch in the TravisCI status image.
> TravisCI status to use master branch

- lib/sites/gog.js
- test/e2e/gog-uris-test.js
- test/unit/sites/gog-test.js
Add support for the site gog.com.
This should close #60.
> Add support for gog.com

- lib/sites/flipkart.js
- test/e2e/flipkart-uris-test.js
- test/unit/sites/flipkart-test.js
Add support for the Flipkart site.  This implementation uses page scraping to obtain the product information.
> Add support for Flipkart

- lib/sites/snapdeal.js
- test/e2e/snapdeal-uris-test.js
- test/unit/sites/snapdeal-test.js
> Snapdeal Added

- README.md
- lib/sites/snapdeal.js
- test/e2e/snapdeal-uris-test.js
- test/unit/sites/snapdeal-test.js
- Update snapdeal queries
- Add new supported sites to readme
> Random updates

- lib/sites/priceminister.js
- test/e2e/priceminister-uris-test.js
The end to end tests are randomly failing for some reason.  Use a different item in the test, and provide additional methods to find the price.
This should fix #84.
> Attempt to fix PriceMinister e2e tests

- lib/site-utils.js
- lib/sites/greenman-gaming.js
- test/e2e/greenman-gaming-uris-test.js
- test/unit/sites/greenman-gaming-test.js
Added Support for greenmangaming.com. This will close #62 .
**UPDATE:** Best Buy e2e fails because from forked repo, it could get the KEYS it needed!! I tried but without knowing key, it is not possible to encrypt/decrypt.
> Greenman Gaming Added

- CHANGELOG.md
- README.md
- package.json
- Update the readme to include the sites added
- Include changes in changelog
- Bump version in package.json, remove unused dependencies, clean up
keywords.
This should close #82.
> Release 4.0.0

- .travis.yml
- lib/sites/crutchfield.js
- lib/sites/gog.js
- lib/sites/greenman-gaming.js
- lib/sites/newegg.js
- test/e2e/best-buy-uris-test.js
- test/e2e/greenman-gaming-uris-test.js
- test/e2e/newegg-uris-test.js
- test/e2e/snapdeal-uris-test.js
- test/unit/sites/crutchfield-test.js
- test/unit/sites/gog-test.js
- test/unit/sites/greenman-gaming-test.js
- Some of the sites have changed how they display price, category, and/or name for their products.  Update the code to account for these changes.
- Update some of the e2e tests also to account for these same changes.
- Travis CI changes:
- Remove the encrypted best buy variables since we no longer require them, and are working to remove that API feature.
- Add Node v6 testing.
> Site fixes, test fixes, travis improvements

- lib/sites/walmart.js
- test/e2e/walmart-uris-test.js
- test/unit/sites/walmart-test.js
This work was done by @rajkumarpb to add support for Walmart.com.  This will resolve #78.
One minor change was done in addition to the work done in PR #91, to add the work suggested by this comment: https://github.com/dylants/price-finder/pull/91#discussion_r56736333
> Add Walmart Support

- CHANGELOG.md
- README.md
- package.json
Update changelog, add new site to documentation, bump version.
> Release 4.1.0

- lib/sites/priceminister.js
- test/e2e/priceminister-uris-test.js
- test/unit/sites/priceminister-test.js
- Remove the old code which was used to retrieve the price and name.
- Add new selectors to find the price and name after the site changes.
- Update the unit tests to align with the changes
- Use an updated product in the e2e test
This should close #99
> Fix priceminister

- CHANGELOG.md
- README.md
- package.json
Update changelog, add new support in readme, bump version.
> Release 4.2.0

- README.md
- lib/sites/thinkgeek.js
- test/e2e/snapdeal-uris-test.js
- test/e2e/thinkgeek-uris-test.js
- test/unit/sites/thinkgeek-test.js
> added support for thinkgeek

- .eslintrc
- lib/price-finder.js
- lib/site-manager.js
- lib/sites/best-buy.js
- lib/sites/newegg.js
- lib/sites/sony-entertainment-network-store.js
- package.json
- test/.eslintrc
- test/e2e/.eslintrc
- test/e2e/test-helper.js
- test/unit/price-finder-test.js
- test/unit/sites/best-buy-test.js
- test/unit/sites/priceminister-test.js
Update the dependencies to the latest versions.  In doing so, there’s a new version of Airbnb’s eslint rules.  Along with that change comes a whole set of things we need to do.  Some of those things just don’t match with the coding style used in this project so far, so some new rules were added to the `.eslintrc` file.  Otherwise, make the changes to the source files.
> Update dependencies / eslint changes

- CHANGELOG.md
- README.md
- package.json
- Add info to changelog, update version, fix readme.
> Release 5.0.0

- CHANGELOG.md
- package.json
- Add info to changelog, update version.
> Release 5.0.1

- CHANGELOG.md
- package.json
- Update changelog and package version
> Release 5.0.2

- .github/workflows/ci.js.yml
- try naming the CI job to require status checks
> require status checks

- src/sites/Amazon.ts
- src/sites/HomeDepot.ts
- test/e2e/HomeDepot.e2e.test.ts
- test/unit/sites/Amazon.test.ts
- test/unit/sites/HomeDepot.test.ts
- Add support for homedepot.com
- clean up some Amazon code
> Home Depot

- CHANGELOG.md
- package.json
> release 6.0.0-alpha.1

- CHANGELOG.md
- package.json
- types/sites/HomeDepot.d.ts
- include the build resources and re-release
> 6.0.0-alpha.2

- .github/workflows/ci.js.yml
- README.md
- package.json
- add support for node 16
- update readme for running single e2e test
> chore: support node 16, single e2e

- README.md
- src/sites/Crutchfield.ts
- test/e2e/Crutchfield.e2e.test.ts
- test/unit/sites/Crutchfield.test.ts
> feat: add Crutchfield site
