dylants/price-finder

README.md
lib/sites/sony-entertainment-network-store.js
test/e2e/sony-entertainment-network-store-uris-test.js
test/unit/sites/sony-entertainment-network-store-test.js

The Sony store has recently changed it’s URL’s from `sonyentertainmentnetwork` to `playstation`.  URL redirects exist for legacy URLs, but we should support both forms.  So update the site to support both the old and new URL, and from here on generate new URLs for the store.

Update Sony store

---

.jshintrc
Gruntfile.js
lib/sites/crutchfield.js
package.json
test/.jshintrc
test/unit/sites/sony-entertainment-network-store-test.js

Update the `.jshintrc` files to be a bit more strict, and in doing so, clean up the code where necessary.  To automate this process, add Grunt support which now runs the tests (but first runs jshint).

Update jshint files, add Grunt for testing

---

README.md
lib/sites/best-buy.js
test/unit/sites/best-buy-test.js

To avoid the case that the user does not have an API key, and they request a price for a BestBuy URL, the error that previously was returned concerned not having a URI to make the page request.  This was because the API key lookup was within the `getURIForPageData` function.
This commit moves that into the constructor of the BestBuy site, so that if the API key is not available on instantiation, we throw an error and include within it the reason why (no API key).  The `getURIForPageData` function can then generate the URI without worrying if the API key exists or not.
Also, change the logic so that the environment variable overrides the configuration.  This allows us the ability to change things in production without a code change.  Mark this as so in the readme.

Improve error handling for BestBuy site

---

lib/sites/amazon.js

Change the selector to something a bit higher level, in the hopes that it works longer.
This closes https://github.com/dylants/price-finder/issues/13.

Fix Amazon books price selector

---

lib/sites/ebags.js

Use a wildcard along with the `itemprop` selector instead of binding it to the `h2`.
This closes https://github.com/dylants/price-finder/issues/14.

Fix eBags price selector

---

.travis.yml

Add Node v4 to the list of Node versions run in the Travis CI test builds.  Everything else seems to work fine with Node v4.
This should close #20.

Node v4 support: update Travis CI versions

---

lib/sites/amazon.js

I’d really rather not include the accordion ID tag in the selector for the books, but Amazon has the same HTML structure for the used and new book price.  So include the new ID tag in the selector, and some additional logging to help determine the issue in the future.
This should close #21.

Fix for Amazon books accordion

---

README.md
lib/site-utils.js
lib/sites/amazon.js
package.json
test/unit/site-utils-test.js

What prompted this was issue #19, which requested Amazon support for additional sites other than “.com”.  In testing of the amazon.fr site, the main check done in `isSite` failed because of the restriction for “.com”.  Loosening this allowed price finder to locate the correct name, but unable to locate the price because of the currency difference.
This commit adds the `accounting` module which gives us the ability to pull the number value from a variety of currencies.  We’ve pulled the logic out of `amazon.js` and into a helper library, `site-utils.js`. Within here, perform an initial check to see which currency type we’re looking at, and then use `accounting` to find the number value, and return it to the user.
With this change the test url provided in the issue returns the correct name …

Support additional currencies (Amazon)

---

README.md
lib/sites/nintendo.js
test/e2e/nintendo-uris-test.js
test/unit/sites/nintendo-test.js

Add a site for nintendo.com, pulling the price and name from the page, and hard coding the category to video games.  Add unit and end to end tests.
This should close issue #15.

Add support for Nintendo.com

---

lib/site-utils.js
test/unit/site-utils-test.js

Add support for Japanese Yen, via the work done by @devil-tamachan.  This is a modification of the original pull request (#31), but with only the first two commits (and not the work that included support for the additional site, Surugaya).

Add Yen support

---

lib/sites/amazon.js
test/e2e/amazon-uris-test.js

Things within the “luggage” category for Amazon seem to at times use a default sale price selector.  So add that in the hopes in covers those cases.  Also add a test to know if things break in the future.
This closes #33.

Add selector to help find luggage items

---

.travis.yml

Since we state that price-finder supports Node v4 and above, add Node v5 to the `.travis.yml` file.

Add node v5 to Travis CI

---

lib/sites/best-buy.js
lib/sites/priceminister.js
lib/sites/sony-entertainment-network-store.js

Make sure all the sites use `siteUtils.processPrice` when processing the price of an item.  In cases where that’s not necessary, call it out in a comment.
This should close #29.

Use processPrice where possible

---

lib/site-utils.js
lib/sites/steam.js
test/unit/site-utils-test.js
test/unit/sites/steam-test.js

The Steam query requires that we limit the scope of the inner queries (for the price) by an outer scope (the first game panel display).  To do this, we’ll first query the outer scope, find the first element, and then pass that to the `siteUtils.findContentOnPage` to perform the inner queries for price.
With this new requirement, we may be passing the original jQuery object or the inner first() one described above to the `findContentOnPage` function.  So update the function to check if the `find()` function is available on the jQuery object, and if so, use that.  Otherwise we proceed as we normally would.

Support find(), improve Steam query

---

lib/price-finder.js

This was a copy/paste bug in assuming it was going to be handled by the logger and the second argument would populate the string template.  Fix this to use a template string.
This should close #48.

Correct callback error string

---

lib/sites/newegg.js
test/e2e/newegg-uris-test.js
test/unit/sites/newegg-test.js

This problem was first found because the end to end tests for Newegg failed, in that they couldn’t find the price on the site.  After some investigation, it appeared that the price was not on the initial HTML page returned from the request call, but perhaps later added to the page?  What’s weird is that this might have worked in the past?  Unsure…
Either way the current method wasn’t working.  Looking at the HTML returned from the request, it looks like the price _is_ available in some javascript near the bottom of the page.  We can get access to this price via a regular expression.
Update the tests to align with these changes.
This should close #49.

Fix Newegg end to end test: findPriceOnPage

---

.travis.yml
Gruntfile.js
lib/price-finder.js
package.json
test/e2e/amazon-uris-test.js
test/e2e/best-buy-uris-test.js
test/e2e/crutchfield-uris-test.js
test/e2e/ebags-uris-test.js
test/e2e/gamestop-uris-test.js
test/e2e/google-play-uris-test.js
test/e2e/infibeam-uris-test.js
test/e2e/newegg-uris-test.js
test/e2e/nintendo-uris-test.js
test/e2e/priceminister-uris-test.js
test/e2e/sony-entertainment-network-store-uris-test.js
test/e2e/steam-uris-test.js
test/e2e/test-helper.js
test/unit/sites/best-buy-test.js

Two general things were done in this pull request around the end to end tests:
- Refactor the tests to pull out common function into a `test-helper.js` file.  This includes the environment variable setup for Jasmine, creating a single price-finder instance, and defining a set of helper test functions.  This resolves #53.
- Add the end to end tests to the Travis CI build.  In order to avoid problems, increase the timeout for each e2e test to a _really_ high value, and set the retry sleep time for price finder's scraping utility to a high value (to avoid spamming).  We also had to include the key to access Best Buy in an encrypted format within the .travis.yml file ([reference Travis CI documentation](https://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables)).  This …

E2E tests: refactor and add to Travis CI

---

README.md
lib/price-finder.js
lib/sites/google-play.js
lib/sites/steam.js
package.json
test/unit/price-finder-test.js
test/unit/sites/google-play-test.js
test/unit/sites/steam-test.js

Replace the node module `request` with `superagent`.  Doing so seems to have greatly improved the reliability of the responses as well as the detail returned (at least in tests of the existing site pages).  We’re no longer seeing all the 503 responses (which were seen a lot on Amazon) and we’re able to get additional page content which makes some of the sites price queries easier.
In issue #63 a few sites were listed as tests to see if we could improve the page response data enough to help those example pages. Newegg still seems to mask their price data too much to allow a single request to return the price as it is displayed on a rendered page. Upon further investigation, if one was to view the page source of a Newegg site, the price data is not included.  This leads one to believe the …

Switch from request to superagent

---

README.md
lib/sites/best-buy.js
test/e2e/best-buy-uris-test.js
test/e2e/flipkart-uris-test.js
test/unit/sites/best-buy-test.js
test/unit/sites/mock-data/bestbuy-other_category.json

Refactor the Best Buy site implementation to support both the API path and the scraping path.  If the API key is available as an environment variable, we’ll use the API to query for product details.  If however it’s not available, then we support scraping the site for the details as well.  This should allow for both those who want to use the API but not restrict those who do not have an API key.
A breaking change is that we no longer support supplying the API key through the configuration of the `PriceFinder` object.  To simplify things, this API key can now only be supplied through an environment variable (which most should use anyway to avoid committing the API key to source control).
Update the tests to account for the changes.  The unit tests check both the API and scraping path.  The …

Best Buy supports both scraping and API

---

lib/site-utils.js
test/unit/site-utils-test.js

Since we `toLowerCase` the price string at the start of the function, we shouldn’t need to `toUpperCase` the string in certain circumstances to make sure it’s in the correct case — we know it’s in lower case.  So remove the upper case logic.
Also add test cases for areas not tested.
This should close #81.

Standardize processPrice

---

lib/sites/best-buy.js
package.json
test/e2e/best-buy-uris-test.js
test/unit/sites/best-buy-test.js

The analytics data which we used to locate the category for Best Buy (when scraping) has changed.  Update to use regex to pull the values from the new analytics data.
Also update the e2e test for Best Buy which had a name change.
This should fix #92.
Additionally, increase the timeout on the `test-e2e-single` script to 10 seconds (default was 2).

Update Best Buy category query

---

lib/sites/flipkart.js
test/e2e/flipkart-uris-test.js
test/unit/sites/flipkart-test.js

Update flipkart to use regex instead of the `itemprop` meta tags (since the site has removed them).  More information about the problem can be found here:
https://github.com/dylants/price-finder/issues/98
This should close #98.

Fix flipkart

---

lib/site-utils.js
lib/sites/amazon.js
test/unit/site-utils-test.js

Finding the price for a video game at Amazon failed because they changed the page content to remove the decimal point from the price. To work around this, we’re now only finding the dollar price and not the cents price.  More information can be found in #97.
This has a side effect of no longer including the currency symbol in the price which we ask `site-utils` to process.  So update `site-utils` to check to see if the price string it gets is a number, and if so, use the defaults in `accounting` to process.  Otherwise, if it’s not a number, continue to return `-1`.
This should close #97.

Defaults for no currency symbol, fix amazon video games

---

lib/sites/target.js
test/e2e/target-uris-test.js
test/unit/sites/target-test.js

Add support for target.com, using the API call rather than the page scrape.  This provides us with more detail than a page scrape, specifically within the categories call, which is simply returning what Target specifies.
This should close #79.

Add support for Target.com

---

README.md
test/e2e/flipkart-uris-test.js
test/e2e/snapdeal-uris-test.js

At this point we’re unable to get the price from a Flipkart site.  For more information on the problem, see:
https://github.com/dylants/price-finder/issues/98
https://github.com/dylants/price-finder/issues/106
So for now, we’re going to state we do NOT support Flipkart, though we’re leaving in the code until we can determine if we should remove it or try to add support back in.
Also, fix a Snapdeal e2e test.
This "kinda" fixes #106.

Flipkart problems

---

lib/sites/amazon.js
lib/sites/newegg.js
test/e2e/amazon-uris-test.js
test/e2e/crutchfield-uris-test.js
test/e2e/snapdeal-uris-test.js

We’ve collected a list of selectors to use for Amazon products. Go through that list, trim it down if possible, and label where each selector is used (at least one place).
In addition to cleaning up the selectors, try to fix a couple issues:
- Use the “more buying options” price when Amazon doesn’t list the price or doesn’t sell it themselves. This should close #112.
- The second issue is when Amazon has a sale price but doesn’t list it in the buy box. Move up the sale price selector higher in the select order to correctly grab it rather than some other price listed in the buy box (insurance, warranty, etc). This should close #113.
Also fix some end to end tests which require changes because of product changes on these sites. And disable an eslint rule within a regex line of code, since …

Amazon fixes, e2e fixes

---

.travis.yml
README.md
lib/price-finder.js
lib/site-utils.js
lib/sites/amazon.js
lib/sites/gog.js
lib/sites/google-play.js
lib/sites/nintendo.js
package.json
test/e2e/amazon-uris-test.js
test/e2e/best-buy-uris-test.js
test/e2e/crutchfield-uris-test.js
test/e2e/gamestop-uris-test.js
test/e2e/gog-uris-test.js
test/e2e/walmart-uris-test.js
test/unit/price-finder-test.js
test/unit/sites/gog-test.js
test/unit/sites/google-play-test.js
test/unit/sites/nintendo-test.js
yarn.lock

**Fix sites**
- Some sites have changed which require updates. Also fix some of the e2e tests to account for product updates.
- Add a request header (User-Agent) to the main call to allow some sites to work.
**Temporarily Disable Site**
- Best Buy looks to have disabled the ability to scrape the site, so temporarily disable the e2e tests. Support is unknown at this time.
**Update dependencies**
- Update the dependencies to latest.
**e2e in CI**
- Disable the e2e tests in CI while the CI boxes are blocked by some sites. Hope to enable it back in the future, but running it locally to verify e2e works for now.

Fix sites, update dependencies

---

.travis.yml
Gruntfile.js
README.md
lib/price-finder.js
lib/sites/crutchfield.js
test/e2e/best-buy-uris-test.js
test/e2e/greenman-gaming-uris-test.js
test/e2e/infibeam-uris-test.js
test/e2e/priceminister-uris-test.js
test/e2e/thinkgeek-uris-test.js
test/unit/sites/crutchfield-test.js

- Enable the e2e tests in CI once again, but skip 2 that are having problems in CI but not locally.
- Fix Crutchfield site logic
- Re-enable BestBuy by setting certain headers in the scrape call.

Enable e2e in CI, fix Crutchfield & BestBuy

---

lib/sites/amazon.js
test/unit/sites/amazon-test.js

~~**Price**~~
- ~~Look in `#usedPrice`, when `#newPrice` is empty and none other selector has price.~~
_Amazon changed the selectors, a day after this commit. Check last commit_
**Category**
- Look in `#wayfinding-breadcrumbs_container ul li span a`, when `data-category` attribute is absent.
e.g. https://www.amazon.com/product/dp/B001AQO446
_Fixes e2e tests_, `testing a Movies & TV item` and `testing a Luggage item`
**Unit Test**
- Write a unit test, `should return the category when displayed on the page, in breadcrums`
**Tweak Price Selectors**
- Amazon has changed how it displays price, for Video Games. Replacing `#newPrice .buyingPrice` with `#newPitchPrice .price-large`, and likewise `#usedPrice .buyingPrice` with `#usedPitchPrice .price-large`.
e.g. …

Amazon fixes
